version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file serverless.yaml --s3-bucket crud-serverless-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - serverless.yaml
    - outputSamTemplate.yaml